apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apisix-ui.fullname" . }}
  labels:
    {{- include "apisix-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.config.adminPassword | quote }}
  {{- if .Values.config.createDefaultEnv }}
  DEFAULT_ENV_NAME: {{ .Values.config.defaultEnvName | quote }}
  DEFAULT_ENV_DISPLAY_NAME: {{ .Values.config.defaultEnvDisplayName | quote }}
  DEFAULT_APISIX_URL: {{ .Values.config.defaultApisixUrl | quote }}
  DEFAULT_APISIX_PASSWORD: {{ .Values.config.defaultApisixPassword | quote }}
  {{- end }}
